#!/bin/bash
echo "🚀 Setting up GitHub auto-deployment for Patrons"
echo ""
echo "1. Go to: https://github.com/new"
echo "2. Repository name: patrons"
echo "3. Description: Patrons - Dynamic worker placement game"
echo "4. Make it Public"
echo "5. DON'T initialize with README (we have files already)"
echo "6. Click 'Create repository'"
echo ""
echo "Then run these commands:"
echo "git remote add origin https://github.com/YOUR_USERNAME/patrons.git"
echo "git push -u origin main"
echo ""
echo "After that, you can deploy with just: git push"
echo ""
echo "For automatic web deployment, go to:"
echo "Repository Settings → Pages → Source: Deploy from a branch → main → / (root)"